version: "3"
volumes:
  datavolume: {}
services:
  ethereum-node:
    container_name: ethereum-node
    image: hydroprotocolio/hydro-scaffold-dex-ethereum-node:latest
    ports:
      - 127.0.0.1:8545:8545
    restart: always
    logging: &logging_default
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200m"
        compress: "true"
  db:
    container_name: pg
    image: postgres
    ports:
      - 127.0.0.1:5432:5432
    restart: always
    volumes:
      - datavolume:/var/lib/postgresql/data
      - ./models/migrations/0001-init.up.sql:/docker-entrypoint-initdb.d/0001-init.up.sql
    #      - ./envs/localhost/seed.sql:/docker-entrypoint-initdb.d/0002-seed.sql
    logging:
      <<: *logging_default
