version: "3"
volumes:
  datavolume: {}
services:
  db:
    container_name: pg
    image: postgres
    ports:
      - 127.0.0.1:5432:5432
    restart: always
    volumes:
      - datavolume:/var/lib/postgresql/data
    logging: &logging_default
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200m"
        compress: "true"
  ethereum-launcher:
    build: ./
    container_name: ethereum-launcher
    image: hydroprotocolio/ethereum-launcher:latest
    command: /bin/app
    ports:
      - 127.0.0.1:3000:3000
      - 127.0.0.1:3001:3001
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/postgres?sslmode=disable
      - ETHEREUM_NODE_URL=https://ropsten.infura.io/v3/cabc724fb9534d1bb245582a74ccf3e7
      - MAX_GAS_PRICE_FOR_RETRY=50000000000
      - RETRY_PENDING_SECONDS_THRESHOLD=90
      - RETRY_PENDING_SECONDS_THRESHOLD_FOR_URGENT=45
      - PRIVATE_KEYS=
    depends_on:
      - db
    restart: always
    logging:
      <<: *logging_default
